<?php
// version 2016-05-13
// deutsch
$trans = array(
  'type=airline' => 'type=go',
  'type=airport' => 'type=go',
  'type=airport service' => 'type=go',
  'type=bus' => 'type=go',
  'type=car rental' => 'type=go',
  'type=car sharing' => 'type=go',
  'type=ferry' => 'type=go',
  'type=marina' => 'type=go',
  'type=port' => 'type=go',
  'type=public transport' => 'type=go',
  'type=shuttle bus service' => 'type=go',
  'type=subway' => 'type=go',
  'type=taxi' => 'type=go',
  'type=train' => 'type=go',
  'type=tram' => 'type=go',
  'type=brown' => 'type=go',
  
  'type=aquarium' => 'type=see',
  'type=archaeological site' => 'type=see',
  'type=botanical garden' => 'type=see',
  'type=bridge' => 'type=see',
  'type=building' => 'type=see',
  'type=bunker' => 'type=see',
  'type=castle' => 'type=see',
  'type=cathedral' => 'type=see',
  'type=cave' => 'type=see',
  'type=cemetery' => 'type=see',
  'type=church' => 'type=see',
  'type=fort' => 'type=see',
  'type=gallery' => 'type=see',
  'type=garden' => 'type=see',
  'type=lake' => 'type=see',
  'type=landmark' => 'type=see',
  'type=memorial' => 'type=see',
  'type=mining museum' => 'type=see',
  'type=monastery' => 'type=see',
  'type=mosque' => 'type=see',
  'type=museum' => 'type=see',
  'type=national park' => 'type=see',
  'type=nunnery' => 'type=see',
  'type=open air museum' => 'type=see',
  'type=opera house' => 'type=see',
  'type=pagoda' => 'type=see',
  'type=palace' => 'type=see',
  'type=park' => 'type=see',
  'type=plantation' => 'type=see',
  'type=pyramid' => 'type=see',
  'type=religious site' => 'type=see',
  'type=sight' => 'type=see',
  'type=stadium' => 'type=see',
  'type=stud' => 'type=see',
  'type=synagogue' => 'type=see',
  'type=temple' => 'type=see',
  'type=tower' => 'type=see',
  'type=town hall' => 'type=see',
  'type=waterfall' => 'type=see',
  'type=zoological garden' => 'type=see',
  'type=steelblue' =>'type=see',
  
  'type=amusement park' => 'type=do',
  'type=ballooning' => 'type=do',
  'type=beach' => 'type=do',
  'type=bike rental' => 'type=do',
  'type=casino' => 'type=do',
  'type=cinema' => 'type=do',
  'type=circus' => 'type=do',
  'type=cultural organization' => 'type=do',
  'type=dive center' => 'type=do',
  'type=dolphinarium' => 'type=do',
  'type=festival' => 'type=do',
  'type=golf' => 'type=do',
  'type=horsecar' => 'type=do',
  'type=massage' => 'type=do',
  'type=mountain' => 'type=do',
  'type=music' => 'type=do',
  'type=quad bike' => 'type=do',
  'type=spa' => 'type=do',
  'type=sport' => 'type=do',
  'type=summit' => 'type=do',
  'type=swimming pool' => 'type=do',
  'type=theater' => 'type=do',
  'type=theme park' => 'type=do',
  'type=grey' => 'type=do',
  
  'type=antiquarian' => 'type=buy',
  'type=bakery' => 'type=buy',
  'type=bank' => 'type=buy',
  'type=bike shop' => 'type=buy',
  'type=book seller' => 'type=buy',
  'type=delicatessen' => 'type=buy',
  'type=jewellery' => 'type=buy',
  'type=mall' => 'type=buy',
  'type=market' => 'type=buy',
  'type=pastry shop' => 'type=buy',
  'type=shop' => 'type=buy',
  'type=sports shop' => 'type=buy',
  'type=teal' => 'type=buy',
  
  'type=brewery' => 'type=eat',
  'type=cafe' => 'type=eat',
  'type=ice cream parlor' => 'type=eat',
  'type=restaurant' => 'type=eat',
  'type=restaurant and bar' => 'type=eat',
  'type=snack bar' => 'type=eat',
  'type=brown' => 'type=eat',
  
  'type=bar' => 'type=drink',
  'type=beer garden' => 'type=drink',
  'type=club' => 'type=drink',
  'type=discotheque' => 'type=drink',
  'type=pub' => 'type=drink',
  'type=black' => 'type=drink',
  
  'type=appartment' => 'type=sleep',
  'type=alpine hut' => 'type=sleep',
  'type=bed and bike' => 'type=sleep',
  'type=boarding house' => 'type=sleep',
  'type=campsite' => 'type=sleep',
  'type=guest house' => 'type=sleep',
  'type=holiday flat' => 'type=sleep',
  'type=hostel' => 'type=sleep',
  'type=hotel' => 'type=sleep',
  'type=hotel garni' => 'type=sleep',
  'type=pension' => 'type=sleep',
  'type=youth hostel' => 'type=sleep',
  'type=navy' => 'type=sleep',
  
  'type=administration' => 'type=other',
  'type=bookcase' => 'type=other',
  'type=clinic' => 'type=other',
  'type=college' => 'type=other',
  'type=company' => 'type=other',
  'type=consulate' => 'type=other',
  'type=cooking class' => 'type=other',
  'type=customs' => 'type=other',
  'type=dentistry' => 'type=other',
  'type=embassy' => 'type=other',
  'type=fire brigade' => 'type=other',
  'type=government' => 'type=other',
  'type=guide' => 'type=other',
  'type=hospital' => 'type=other',
  'type=internet café' => 'type=other',
  'type=kindergarten' => 'type=other',
  'type=laundry' => 'type=other',
  'type=library' => 'type=other',
  'type=nursery' => 'type=other',
  'type=office' => 'type=other',
  'type=organisation' => 'type=other',
  'type=pharmacy' => 'type=other',
  'type=phone' => 'type=other',
  'type=photo store' => 'type=other',
  'type=practice' => 'type=other',
  'type=police' => 'type=other',
  'type=post' => 'type=other',
  'type=relief organisation' => 'type=other',
  'type=school' => 'type=other',
  'type=shipping company' => 'type=other',
  'type=surgery' => 'type=other',
  'type=toilet' => 'type=other',
  'type=tour operator' => 'type=other',
  'type=tourism authority' => 'type=other',
  'type=tourist information' => 'type=other',
  'type=travel agency' => 'type=other',
  'type=university' => 'type=other',
  'type=forstgreen' => 'type=other'
);
?>
