<?php
// version 2017-01-30
// deutsch
$trans = array(
  'type=aerialway' => 'type=go',
  'type=airline' => 'type=go',
  'type=airport' => 'type=go',
  'type=airport service' => 'type=go',
  'type=bicycle rental' => 'type=go',
  'type=bicycle parking' => 'type=go',
  'type=boat rental' => 'type=go',
  'type=boat sharing' => 'type=go',
  'type=border control' => 'type=go',
  'type=bus' => 'type=go',
  'type=car rental' => 'type=go',
  'type=car repair' => 'type=go',
  'type=car sharing' => 'type=go',
  'type=ferry' => 'type=go',
  'type=fuel' => 'type=go',
  'type=marina' => 'type=go',
  'type=motorbike rental' => 'type=go',
  'type=parking' => 'type=go',
  'type=port' => 'type=go',
  'type=public transport' => 'type=go',
  'type=shipping company' => 'type=go',
  'type=shuttle bus service' => 'type=go',
  'type=station' => 'type=go',
  'type=subway' => 'type=go',
  'type=taxi' => 'type=go',
  'type=train' => 'type=go',
  'type=tram' => 'type=go',
  'type=waypoint' => 'type=go',
  'type=brown' => 'type=go',

  'type=aquarium' => 'type=see',
  'type=archaeological site' => 'type=see',
  'type=artwork' => 'type=see',
  'type=bay' => 'type=see',
  'type=botanical garden' => 'type=see',
  'type=bridge' => 'type=see',
  'type=building' => 'type=see',
  'type=bunker' => 'type=see',
  'type=canal' => 'type=see',
  'type=castle' => 'type=see',
  'type=cathedral' => 'type=see',
  'type=cave' => 'type=see',
  'type=cemetery' => 'type=see',
  'type=church' => 'type=see',
  'type=crocodile farm' => 'type=see',
  'type=farm' => 'type=see',
  'type=forest' => 'type=see',
  'type=fort' => 'type=see',
  'type=gallery' => 'type=see',
  'type=garden' => 'type=see',
  'type=gate' => 'type=see',
  'type=habitat' => 'type=see',
  'type=island' => 'type=see',
  'type=lake' => 'type=see',
  'type=landmark' => 'type=see',
  'type=landscape' => 'type=see',
  'type=mausoleum' => 'type=see',
  'type=memorial' => 'type=see',
  'type=mill' => 'type=see',
  'type=mining museum' => 'type=see',
  'type=monastery' => 'type=see',
  'type=monument' => 'type=see',
  'type=mosque' => 'type=see',
  'type=museum' => 'type=see',
  'type=national park' => 'type=see',
  'type=nature reserve' => 'type=see',
  'type=nunnery' => 'type=see',
  'type=observatory' => 'type=see',
  'type=open air museum' => 'type=see',
  'type=pagoda' => 'type=see',
  'type=palace' => 'type=see',
  'type=park' => 'type=see',
  'type=pedestrian' => 'type=see',
  'type=peninsula' => 'type=see',
  'type=planetarium' => 'type=see',
  'type=plantation' => 'type=see',
  'type=pyramid' => 'type=see',
  'type=religious site' => 'type=see',
  'type=road' => 'type=see',
  'type=sight' => 'type=see',
  'type=spring' => 'type=see',
  'type=square' => 'type=see',
  'type=stud' => 'type=see',
  'type=synagogue' => 'type=see',
  'type=temple' => 'type=see',
  'type=tomb' => 'type=see',
  'type=tower' => 'type=see',
  'type=town hall' => 'type=see',
  'type=tumulus' => 'type=see',
  'type=viewpoint' => 'type=see',
  'type=war grave' => 'type=see',
  'type=waterfall' => 'type=see',
  'type=well' => 'type=see',
  'type=wetland' => 'type=see',
  'type=zoo' => 'type=see',
  'type=zoological garden' => 'type=see',
  'type=steelblue' =>'type=see',

  'type=arts centre' => 'type=do',
  'type=cabaret' => 'type=do',
  'type=cinema' => 'type=do',
  'type=circus' => 'type=do',
  'type=edutainment' => 'type=do',
  'type=fair' => 'type=do',
  'type=festival' => 'type=do',
  'type=music' => 'type=do',
  'type=opera house' => 'type=do',
  'type=puppet theater' => 'type=do',
  'type=theater' => 'type=do',

  'type=amusement park' => 'type=do',
  'type=attraction' => 'type=do',
  'type=ballooning' => 'type=do',
  'type=casino' => 'type=do',
  'type=dolphinarium' => 'type=do',
  'type=entertainment' => 'type=do',
  'type=horsecar' => 'type=do',
  'type=massage' => 'type=do',
  'type=sauna' => 'type=do',
  'type=spa' => 'type=do',
  'type=theme park' => 'type=do',

  'type=9pin' => 'type=do',
  'type=10pin' => 'type=do',
  'type=badminton' => 'type=do',
  'type=beach' => 'type=do',
  'type=beachvolleyball' => 'type=do',
  'type=billiards' => 'type=do',
  'type=bmx' => 'type=do',
  'type=boules' => 'type=do',
  'type=canoe' => 'type=do',
  'type=canyoning' => 'do',
  'type=climbing' => 'type=do',
  'type=cricket' => 'type=do',
  'type=dive center' => 'type=do',
  'type=equestrian' => 'type=do',
  'type=fishing' => 'type=do',
  'type=fitness centre' => 'type=do',
  'type=golf' => 'type=do',
  'type=horse racing' => 'type=do',
  'type=hunting' => 'type=do',
  'type=ice hockey' => 'type=do',
  'type=karting' => 'type=do',
  'type=kitesurfing' => 'type=do',
  'type=minigolf' => 'type=do',
  'type=motocross' => 'type=do',
  'type=mountain' => 'type=do',
  'type=orienteering' => 'type=do',
  'type=paragliding' => 'type=do',
  'type=quad bike' => 'type=do',
  'type=roller skating' => 'type=do',
  'type=racetrack' => 'type=do',
  'type=rowing' => 'type=do',
  'type=sailing' => 'type=do',
  'type=scuba diving' => 'type=do',
  'type=ski school' => 'do',
  'type=soccer' => 'type=do',
  'type=sport' => 'type=do',
  'type=sports' => 'type=do',
  'type=stadium' => 'type=do',
  'type=summit' => 'type=do',
  'type=surfing' => 'do',
  'type=swimming' => 'type=do',
  'type=swimming pool' => 'type=do',
  'type=tennis' => 'type=do',
  'type=water ski' => 'type=do',
  'type=water sports' => 'type=do',
  'type=grey' => 'type=do',

  'type=antiquarian' => 'type=buy',
  'type=atm' => 'type=buy',
  'type=bakery' => 'type=buy',
  'type=bank' => 'type=buy',
  'type=beverages' => 'type=buy',
  'type=bike shop' => 'type=buy',
  'type=book seller' => 'type=buy',
  'type=boutique' => 'type=buy',
  'type=butchery' => 'type=buy',
  'type=carpet shop' => 'type=buy',
  'type=chemist' => 'type=buy',
  'type=collector shop' => 'type=buy',
  'type=cosmetics shop' => 'type=buy',
  'type=crafts shop' => 'type=buy',
  'type=delicatessen' => 'type=buy',
  'type=department store' => 'type=buy',
  'type=fashion store' => 'type=buy',
  'type=flea market' => 'type=buy',
  'type=hairdresser' => 'type=buy',
  'type=jewellery' => 'type=buy',
  'type=kiosk' => 'type=buy',
  'type=mall' => 'type=buy',
  'type=market' => 'type=buy',
  'type=music shop' => 'type=buy',
  'type=optician' => 'type=buy',
  'type=outdoor retailer' => 'type=buy',
  'type=pastry shop' => 'type=buy',
  'type=photo store' => 'type=buy',
  'type=second hand' => 'type=buy',
  'type=shop' => 'type=buy',
  'type=souvenir shop' => 'type=buy',
  'type=sports shop' => 'type=buy',
  'type=supermarket' => 'type=buy',
  'type=watersports shop' => 'type=buy',
  'type=teal' => 'type=buy',

  'type=bistro' => 'type=eat',
  'type=brasserie' => 'type=eat',
  'type=brewery' => 'type=eat',
  'type=cafe' => 'type=eat',
  'type=cafeteria' => 'type=eat',
  'type=canteen' => 'type=eat',
  'type=coffee shop' => 'type=eat',
  'type=fast food' => 'type=eat',
  'type=ice cream' => 'type=eat',
  'type=restaurant' => 'type=eat',
  'type=restaurant and bar' => 'type=eat',
  'type=snack bar' => 'type=eat',
  'type=steak house' => 'type=eat',
  'type=brown' => 'type=eat',

  'type=bar' => 'type=drink',
  'type=beer garden' => 'type=drink',
  'type=club' => 'type=drink',
  'type=discotheque' => 'type=drink',
  'type=distillery' => 'type=drink',
  'type=nightclub' => 'type=drink',
  'type=pub' => 'type=drink',
  'type=vineyard' => 'type=drink',
  'type=black' => 'type=drink',

  'type=appartment' => 'type=sleep',
  'type=alpine hut' => 'type=sleep',
  'type=bed and bike' => 'type=sleep',
  'type=boarding house' => 'type=sleep',
  'type=campsite' => 'type=sleep',
  'type=caravan site' => 'type=sleep',
  'type=chalet' => 'type=sleep',
  'type=guest house' => 'type=sleep',
  'type=holiday flat' => 'type=sleep',
  'type=hostel' => 'type=sleep',
  'type=hotel' => 'type=sleep',
  'type=hotel garni' => 'type=sleep',
  'type=motel' => 'type=sleep',
  'type=pension' => 'type=sleep',
  'type=resort' => 'type=sleep',
  'type=wilderness hut' => 'type=sleep',
  'type=youth hostel' => 'type=sleep',
  'type=navy' => 'type=sleep',

  'type=clinic' => 'type=other',
  'type=dentistry' => 'type=other',
  'type=health' => 'type=other',
  'type=health centre' => 'type=other',
  'type=hospital' => 'type=other',
  'type=laboratory' => 'type=other',
  'type=naturopathy' => 'type=other',
  'type=nursing home' => 'type=other',
  'type=pharmacy' => 'type=other',
  'type=practice' => 'type=other',
  'type=rehabilitation' => 'type=other',
  'type=surgery' => 'type=other',
  'type=veterinary' => 'type=other',

  'type=bookcase' => 'type=other',
  'type=college' => 'type=other',
  'type=cooking class' => 'type=other',
  'type=kindergarten' => 'type=other',
  'type=language school' => 'type=other',
  'type=library' => 'type=other',
  'type=nursery' => 'type=other',
  'type=school' => 'type=other',
  'type=university' => 'type=other',

  'type=administration' => 'type=other',
  'type=company' => 'type=other',
  'type=consulate' => 'type=other',
  'type=customs' => 'type=other',
  'type=cultural organisation' => 'type=other',
  'type=embassy' => 'type=other',
  'type=fire brigade' => 'type=other',
  'type=government' => 'type=other',
  'type=guide' => 'type=other',
  'type=internet cafe' => 'type=other',
  'type=laundry' => 'type=other',
  'type=lost and found' => 'type=other',
  'type=mobile telephony' => 'type=other',
  'type=office' => 'type=other',
  'type=organisation' => 'type=other',
  'type=phone' => 'type=other',
  'type=police' => 'type=other',
  'type=post' => 'type=other',
  'type=relief organisation' => 'type=other',
  'type=shelter' => 'other',
  'type=toilet' => 'type=other',
  'type=tour operator' => 'type=other',
  'type=tourism authority' => 'type=other',
  'type=tourist information' => 'type=other',
  'type=travel agency' => 'type=other',
  'type=forestgreen' => 'type=other',

  'type=scenic view' => 'type=view',

  'type=settlement' => 'type=city',
  'type=village' => 'type=city'
);
?>
